# 项目环境配置

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # serverTimezone 设置数据库时区
    url: jdbc:mysql://localhost:3306/user?serverTimezone=UTC
    username: root
    password: rootroot

# mybatis-plus配置数据库自增策略
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
