# 本地环境配置
# 服务端口
server:
  port: 8080

# devtools热部署相关配置
spring:
  devtools:
    restart:
      # 设置是否开启热部署
      enabled: false
      # 设置不参与热部署的文件或者文件夹
      exclude: config/**,static/**,public/**

# mybatis-plus 配置日志输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印到控制台

env:
  name: dev
  timeout: 3
  data-size: 10