# 本地环境配置
# 服务端口
server:
  port: 8080

# devtools热部署相关配置
spring:
  devtools:
    restart:
      # 设置是否开启热部署
      enabled: false
      # 设置不参与热部署的文件或者文件夹
      exclude: config/**,static/**,public/**

  # h2数据库配置
  h2:
    console:
      enabled: false
      path: /h2
  # mail配置
  mail:
    host: smtp.163.com
    username: xxx@163.com
    password: xxx

# mybatis-plus 配置日志输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印到控制台

configs:
  name: dev
  num: 1999
  timeout: 3
  data-size: 10
